# Generated by Django 4.2.6 on 2023-10-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_label', '0001_initial'),
        ('core_user', '0003_user_avatar_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts_liked',
            field=models.ManyToManyField(related_name='liked_by', to='core_label.post'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
