# Generated by Django 4.2.6 on 2023-11-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0004_user_posts_liked_alter_user_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_directory_path'),
        ),
    ]
